#!/opt/local/bin/perl -w

use strict;
use JSON;
use Data::Dumper;
use Finance::QIF;
use Time::Local;
use Getopt::Std;

my $kmtomile = 0.621371192;

sub usage {
	die "Usage: $0 [ -q ] [ -s start ] [ -e end ] [ -d days ]\n" .
	    "       -q: QIF output\n" .
	    "       -s|-e: restrict time range to start/end in YYYYMMDD format\n" .
	    "       -d: only match <days> of the week regex\n";
}

our($opt_q, $opt_s, $opt_e, $opt_d);
getopts('qs:e:d:') || usage();

# set the IFS - not needed as the JSON has no field separators
#my $fs = $/;
#undef $/;
# suck in the JSON on stdin
my $json = <STDIN>;
#$/ = $fs;

# clean up rogue periods from Moves Export data
$json =~ s/\[,\{/\[\{/; # at start
$json =~ s/\},\]/\}\]/; # at end

# translate the JSON into a multi-level perl structure
my $hash = decode_json($json);

# Init the QIF in stdout
my $out = Finance::QIF->new(file => ">-",);
my $header = "Type:Bank";
if ($opt_q) {
	$out->header($header);
}

# Parse the Moves data structure
# Pull out and sum-up the daily transport distances
my $days = $hash->{export};
#print Dumper(@$days);
while (my $day = shift @$days) {
	#print Dumper($day);
	my $total = 0;
	# trp range
	my $start = 999999;
	my $end = 0;

	#print "$date\n";
	while (my $segment = shift @{$day->{segments}} ) {
		# Is this a move entry?
		next unless ($segment->{type} eq 'move');

		#print $segment->{startTime} . "\n";
		# YYYYMMDDTHHMMSSZ
		#$segment->{endTime};
		while (my $activity = shift @{$segment->{activities}}) {
			# Is this a transport entry?
			next unless ($activity->{activity} eq "trp");

			$total += $activity->{distance};

			# earliest start - latest end
			$activity->{startTime} =~ /\d{6}T(\d{6})Z/;
			$start = $1 if ($1 < $start);
			$activity->{endTime} =~ /\d{6}T(\d{6})Z/;
			$end = $1 if ($1 > $end);
		}
	}

	# any transport today?
	next unless $total;

	#my $movesdate = $day->{date};
	#die "'$movesdate'" unless ($movesdate =~ /^(\d{4})(\d{2})(\d{2})$/);
	my $datestart = $day->{date} . $start;
	die "'$datestart'" unless ($datestart =~ /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/);
	my $qifdate = "$3/$2/$1";
	#my $wday = (localtime(timelocal(0,0,0,$3,$2-1,$1)))[6];
	#my $date = localtime(timelocal(0,0,0,$3,$2-1,$1));
	my $date = localtime(timelocal($6,$5,$4,$3,$2-1,$1));

	my $km = $total / 1000;
	my $miles = $km * $kmtomile;

	if (!$opt_q) {
		#printf "Daily total for %s-%d: %.2fMiles (%.2fKm)\n", $date, $wday, $miles, $km;
		printf "%s (-%06d): %6.2f miles (%6.2f Km)\n", $date, $end, $miles, $km;
		next;
	}

	# create a QIF transaction
	my $record = {
		header => $header,
		date => $qifdate,
		transaction => sprintf("%.2f", $miles),
		#total => $miles,
		#status => ,
		payee => 'Drive',
		memo => 'From Moves Export data',
		category => 'Automotive:Fuel:Miles',
	};
	# write out the QIF transaction
	$out->write($record);

}
# close the QIF
$out->close if ($opt_q);
