#!/opt/local/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Finance::QIF;
use Time::Local;
use Getopt::Std;
use POSIX qw(strftime);

use DateTime;
use DateTime::Span;
use DateTime::SpanSet;
use DateTime::Format::Strptime;
use DateTime::Format::ISO8601;

my $kmtomile = 0.621371192;
my @wdays = qw(Sun Mon Tue Wed Thu Fri Sat);
my $miles_tot = 0;
my $spanset_bfilter;

sub usage {
	die "Usage: $0 [ -i ] [ -p <text> ] [ -s|e <YYYYMMDD> ] [ -x|y <HHMMSS> ] [ -d <days_regex> ]\n" .
	    "       -i: output daily summary instead of QIF\n" .
	    "       -p: add freeform <text> to QIF memo\n" .
	    "       -s: ignore dates before YYYYMMDD\n" .
	    "       -e: ignore dates after YYYYMMDD\n" .
	    "       -x: ignore activities starting before HHMMSS on any day\n" .
	    "       -y: ignore activities starting after HHMMSS on any day\n" .
	    "       -d: ignore days of the week not matching <days_regex>\n";
}

sub build_blackout {
	#my $parse = DateTime::Format::Strptime->new(
	#	pattern => '%F %T',
	#	on_error => 'croak',
	#);
	my $parse = DateTime::Format::ISO8601->new;

	my $file = "blackout.csv";
	open(my $data, '<', $file) or die "Could not open '$file' $!\n";
 	
	my $span;
	# drop the header row
	<$data>;
	while (<$data>) {
		s/\s+$//;
		my @fields = split(',');

		# notes, who, DoW, start time, start date, end time, end date
		my $dow = $fields[2];
		my $time1 = $fields[3] ? "T" . $fields[3] : '';
		my $time2 = $fields[5] ? "T" . $fields[5] : 'T23:59:59';
		my $dt1 = $parse->parse_datetime($fields[4] . $time1);
		my $dt2 = $parse->parse_datetime($fields[4] . $time2);
		my $dt3 = $parse->parse_datetime($fields[6] . $time1);

		do {
			# does this date match DoW?
			next unless(!$dow || $dt1->day_abbr() =~ /$dow/i);
			push @$span, DateTime::Span->from_datetimes(start => $dt1->clone(), 
								    end   => $dt2->clone());
			# cycle days in each dates range
			$dt1->add(days => 1);
			$dt2->add(days => 1);
		} until ($dt2 > $dt3);
	}
	close($data);

	# FIXME need to manage different who's
	$spanset_bfilter = DateTime::SpanSet->from_spans(spans => $span);

	#print Dumper($spanset_bfilter->as_list);
	my $iter = $spanset_bfilter->iterator;
	while (my $dt = $iter->next) {
		# $dt is a DateTime::Span
		print $dt->start->datetime . " - " . $dt->end->datetime . "\n";
        }
}

# pretty-print the time
sub hm {
	my $t = $_[0];
	return "no_time" unless $t =~ /^(\d\d)(\d\d)(\d\d)$/;
	return "$1:$2";
}

# FIXME
# use DateTime::Span and DateTime::SpanSet to define all of the blackout SpanSets per user
build_blackout();
exit;

my $memo = " (" . join(' ', @ARGV) . ")";
our($opt_i, $opt_p, $opt_s, $opt_e, $opt_d, $opt_x, $opt_y);
getopts('ip:s:e:d:x:y:') || usage();

# set the IFS (required for human-readable JSON data sources)
my $fs = $/;
undef $/;
# suck in the JSON on stdin
my $json = <STDIN>;
$/ = $fs;

# clean up rogue periods from Moves Export data
$json =~ s/\[,\{/\[\{/; # at start
$json =~ s/\},\]/\}\]/; # at end

# remove double periods
$json =~ s/,,/,/g;

# translate the JSON into a multi-level perl structure
sub moves_json {
	use JSON "decode_json";
	return decode_json($json);
}
my $hash = moves_json();

my $out = Finance::QIF->new(file => ">-",);
my $header = "Type:Bank";
my $payee = "Driving";
my $category = '[Metered consumables:Fuel Tank]';

# Parse the Moves data structure
# Pull out and sum-up the daily transport distances
my $day;
foreach(sort keys @$hash) {
	if (ref $hash->{$_} eq "ARRAY") {
		$day = shift @{$hash->{$_}};
	} else {
		print Dumper($hash->{$_});
		next;
	}

	#print Dumper($day);
	my $total = 0;
	# trp time range in HHMMSS
	my $start = 235959;
	my $end = 0;

	# within date range?
	next unless (!$opt_s || $day->{date} ge $opt_s);
	next unless (!$opt_e || $day->{date} le $opt_e);

	while (my $segment = shift @{$day->{segments}} ) {
		# Is this a move entry?
		next unless ($segment->{type} eq 'move');

		# Moves time format is <YYYY><MM><DD>T<HH><MM><SS>Z
		while (my $activity = shift @{$segment->{activities}}) {
			# Is this a transport entry?
			next unless ($activity->{activity} eq "trp" ||
				     $activity->{activity} eq "transport");

			# earliest start...
			$activity->{startTime} =~ /(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z|\+|\-)/;
			my $stm = strftime("%H%M%S", localtime(timegm($6, $5, $4, $3, $2-1, $1)));
			next unless (!$opt_x || $stm ge $opt_x);
			next unless (!$opt_y || $stm le $opt_y);
			# could we explicitly set $start = strftime(...) ??
			# only if start times are always progressive...
			$start = $stm if ($stm < $start);

			# ...to latest end
			$activity->{endTime} =~ /(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z|\+|\-)/;
			my $etm = strftime("%H%M%S", localtime(timegm($6, $5, $4, $3, $2-1, $1)));
			$end = $etm if ($etm > $end);

			$total += $activity->{distance};
		}
	}

	# any transport today?
	next unless ($total);

	my $datestart = $day->{date} . $start;
	die "'$datestart'" unless ($datestart =~ /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/);
	my $qifdate = "$3/$2/$1";
	my $wday = (localtime(timegm(0,0,0,$3,$2-1,$1)))[6];
	my $date = localtime(timegm($6,$5,$4,$3,$2-1,$1));

	# matches day(s) of week?
	next unless (!$opt_d || $wdays[$wday] =~ /$opt_d/i);

	# issue a header line if we haven't already done so
	$out->header($header) unless ($opt_i || $miles_tot);

	my $km = $total / 1000;
	my $miles = $km * $kmtomile;
	$miles_tot += $miles;

	if ($opt_i) {
		printf "%s (%s-%s) = %6.2f miles (%6.2f Km)\n", $date, hm($start), hm($end), $miles, $km;
		next;
	}

	# create a QIF transaction
	my $record = {
		header => $header,
		date => $qifdate,
		transaction => sprintf("%.3f", $miles),
		payee => $payee,
		memo => hm($start) . "-" . hm($end) . $memo,
		category => $category,
	};
	# write out the QIF transaction
	$out->write($record);

}
# close the QIF
if ($opt_i) {
	printf "Total miles travelled during period:     %6.2f\n", $miles_tot;
} else {
	$out->close;
}
